### ISSUE TITLE
Add instructions on how to use it

### ISSUE THREAD

**Issue by jtrees** [nooulaif/cinnamon-sane-menu#5]
I'm really interested in using this but I don't know how. Could you add some instructions to the README?

**Comment by nooulaif** [comment]
I have added some instructions to README. Can you look and tell me if they are clear enough?

**Comment by jtrees** [comment]
Thanks. They are good. Unfortunately the search doesn't work for me and instead causes Cinnamon to crash. I am still on Linux Mint 17.3. Is Linux Mint 18 a dependency?

**Comment by nooulaif** [comment]
Probably, yes. I have never checked. Fact is it's a fork of menu that comes with Cinnamon 3.0, so maybe that's a source of the problem. I will add this to README.

**Comment by nooulaif** [comment]
I will close this issue for now. If you encounter more problems in the future, please open a new one. Sadly I lack skill for backporting it for older versions of Cinnamon, so currently I cannot help you.
