### ISSUE TITLE
Favor exact matches when searching

### ISSUE THREAD

**Issue by Vhin** [nooulaif/cinnamon-sane-menu#7]
While the search in this is much better than that of the standard Cinnamon menu, there's still some weirdness.

In particular, there are cases where exact matches aren't given as the first result. For example, on my system, if I search for "atom", there are two results, one of which is Atom, but the first result is GIMP (I'm not positive why GIMP is even a search result at all, but that's not relevant to this issue).

Interestingly, if I search for "at" or "ato", Atom is the first result, and GIMP is much further down.

The same thing happens with Color and Color Profile Viewer - searching for "color" gives Color Profile Viewer as the first result, but "colo" gives Color as the first result.

Is there any way to ensure that exact matches are always listed first?

**Comment by nooulaif** [comment]
Thank you for pointing that out. I didn't even noticed.

I can reproduce it with "LibreOffice" and "LibreOffice Writer" so it should be fixed soon.

**Comment by nooulaif** [comment]
Hello @Vhin,

can you execute

```bash
wget -qO- https://raw.githubusercontent.com/nooulaif/cinnamon-sane-menu/master/applet.js > ~/.local/share/cinnamon/applets/sane-menu@nooulaif/applet.js
```

restart Cinnamon and tell me if it fixed your problem?

**Comment by Vhin** [comment]
Yes. It works perfectly.

Thank you.

**Comment by nooulaif** [comment]
No problem. Glad I could help.
