### ISSUE TITLE
Doesn't seem to load on cinnamon 3.2/Mint 18.1

### ISSUE THREAD

**Issue by spicypixel-** [nooulaif/cinnamon-sane-menu#8]
Fairly self explanatory, and going back to the stock menu is a jarring unpleasant experience when using keyboard search.

Suspect, well almost sure, that Cinamon is checking the value in [this](https://github.com/linuxmint/Cinnamon/blob/master/files/usr/share/cinnamon/applets/menu%40cinnamon.org/metadata.json) vs yours and not seeing it as 3.0+ but just 3.0.

**Comment by spicypixel-** [comment]
Can confirm applet works as intended if I remove the version check from metadata.json and log out and back in.

**Comment by nooulaif** [comment]
Thank you. I wasn't sure if it would just work with 3.2 and I have no way of checking it myself right now.
Will release new version soon.

**Comment by spicypixel-** [comment]
Haven't noticed anything broken but I'll file a different issue if I see
anything unexpected.
